import {
  PatientProfile,
  Doctor,
  Hospital,
  Appointment,
  QueueEntry,
  Notification,
  AuditEvent,
  AIRecommendation,
  NetworkStats,
  RecordAccess,
  GlucoseReading,
  TimelineEvent,
  HospitalBed,
  StaffMember,
  ConsultationRecord,
  OpdDepartment,
} from "./types";

// ─── INITIAL PATIENT PROFILE ──────────────────────────────────────────────────
export const defaultPatientProfile: PatientProfile = {
  id: "DIA-204829",
  name: "Rahul Sharma",
  age: 47,
  gender: "Male",
  phone: "+91 98765 43210",
  email: "rahul.s@email.com",
  diabetesType: "Type 2",
  diagnosisYear: 2018,
  heightCm: 172,
  weightKg: 76,
  bmi: 25.7,
  bloodPressure: "124/82",
  hba1c: 7.2,
  medicationInfo: "Metformin 500mg twice daily (BD), Glimepiride 1mg once daily (OD)",
  lastConsultation: "2026-09-10",
  nextFollowUp: "2026-10-15",
  connectedHospitals: ["h1", "h2", "h4"],
  assignedDoctors: ["d1", "d3"],
  totalVisits: 7,
  documents: 12,
  language: "English",
  caregiverAccess: {
    name: "Vikram Sharma",
    relationship: "Son",
    permissions: ["appointments", "queue", "notifications"],
    authorized: true,
  },
};

// ─── INITIAL GLUCOSE READINGS ────────────────────────────────────────────────
export const defaultGlucoseReadings: GlucoseReading[] = [
  {
    id: "gl-001",
    patientId: "DIA-204829",
    date: "2026-10-03",
    time: "08:15 AM",
    value: 118,
    readingType: "Fasting",
    notes: "Fasting morning test before breakfast",
    createdAt: "2026-10-03T08:15:00Z",
  },
  {
    id: "gl-002",
    patientId: "DIA-204829",
    date: "2026-10-02",
    time: "02:30 PM",
    value: 154,
    readingType: "After Meal",
    notes: "2 hours post lunch",
    createdAt: "2026-10-02T14:30:00Z",
  },
  {
    id: "gl-003",
    patientId: "DIA-204829",
    date: "2026-10-01",
    time: "08:00 AM",
    value: 124,
    readingType: "Fasting",
    notes: "Slight headache",
    createdAt: "2026-10-01T08:00:00Z",
  },
  {
    id: "gl-004",
    patientId: "DIA-204829",
    date: "2026-09-29",
    time: "07:45 PM",
    value: 138,
    readingType: "Before Meal",
    notes: "Before dinner",
    createdAt: "2026-09-29T19:45:00Z",
  },
  {
    id: "gl-005",
    patientId: "DIA-204829",
    date: "2026-09-27",
    time: "08:30 AM",
    value: 112,
    readingType: "Fasting",
    notes: "Good exercise yesterday",
    createdAt: "2026-09-27T08:30:00Z",
  },
  {
    id: "gl-006",
    patientId: "DIA-204829",
    date: "2026-09-25",
    time: "03:00 PM",
    value: 172,
    readingType: "After Meal",
    notes: "Post festive meal",
    createdAt: "2026-09-25T15:00:00Z",
  },
];

// ─── INITIAL TIMELINE EVENTS ────────────────────────────────────────────────
export const defaultTimelineEvents: TimelineEvent[] = [
  {
    id: "tl-001",
    patientId: "DIA-204829",
    date: "03 Oct 2026",
    timestamp: "2026-10-03T08:15:00Z",
    title: "Glucose Reading Recorded",
    description: "Fasting: 118 mg/dL (Normal Range)",
    type: "glucose_reading",
  },
  {
    id: "tl-002",
    patientId: "DIA-204829",
    date: "01 Oct 2026",
    timestamp: "2026-10-01T11:00:00Z",
    title: "Doctor Consultation Completed",
    description: "Dr. Ayesha Khan · City Diabetes Centre — Adjusted Metformin timing.",
    type: "consultation",
  },
  {
    id: "tl-003",
    patientId: "DIA-204829",
    date: "25 Sep 2026",
    timestamp: "2026-09-25T10:00:00Z",
    title: "HbA1c Lab Result Updated",
    description: "HbA1c: 7.2% (Target < 7.0%)",
    type: "hba1c_update",
  },
  {
    id: "tl-004",
    patientId: "DIA-204829",
    date: "24 Sep 2026",
    timestamp: "2026-09-24T09:30:00Z",
    title: "OPD Appointment Booked",
    description: "City Diabetes Centre with Dr. Ayesha Khan (Token #18)",
    type: "appointment_booked",
  },
  {
    id: "tl-005",
    patientId: "DIA-204829",
    date: "10 Sep 2026",
    timestamp: "2026-09-10T11:00:00Z",
    title: "Regular OPD Checkup",
    description: "Dr. Priya Mehta · Metro Hospital — BP 124/82, Weight 76 kg",
    type: "consultation",
  },
];

// ─── HOSPITALS ────────────────────────────────────────────────────────────────
export const defaultHospitals: Hospital[] = [
  {
    id: "h1",
    name: "City Diabetes Centre",
    area: "Bandra West",
    city: "Mumbai",
    status: "operational",
    opdCapacityPercent: 82,
    bedsAvailable: { general: 12, icu: 2, observation: 4, total: 35, occupied: 17, reserved: 0, maintenance: 0 },
    doctorsAvailable: 12,
    doctorsTotal: 15,
    appointmentsToday: 184,
    walkIns: 27,
    cancelledSlots: 9,
    availableSlots: 4,
    avgWaitMinutes: 18,
    departments: ["Endocrinology", "Diabetology", "Podiatry", "Ophthalmology", "Nutrition"],
  },
  {
    id: "h2",
    name: "Metro Hospital",
    area: "Andheri East",
    city: "Mumbai",
    status: "operational",
    opdCapacityPercent: 67,
    bedsAvailable: { general: 8, icu: 1, observation: 2, total: 25, occupied: 14, reserved: 0, maintenance: 0 },
    doctorsAvailable: 9,
    doctorsTotal: 12,
    appointmentsToday: 152,
    walkIns: 19,
    cancelledSlots: 4,
    availableSlots: 8,
    avgWaitMinutes: 14,
    departments: ["Internal Medicine", "Endocrinology", "Diabetology", "Nephrology"],
  },
  {
    id: "h3",
    name: "Central Hospital",
    area: "Dadar",
    city: "Mumbai",
    status: "high-load",
    opdCapacityPercent: 94,
    bedsAvailable: { general: 2, icu: 0, observation: 1, total: 20, occupied: 17, reserved: 0, maintenance: 0 },
    doctorsAvailable: 6,
    doctorsTotal: 10,
    appointmentsToday: 201,
    walkIns: 38,
    cancelledSlots: 2,
    availableSlots: 0,
    avgWaitMinutes: 41,
    departments: ["Endocrinology", "General Medicine", "Cardiology"],
  },
  {
    id: "h4",
    name: "Community Health Centre",
    area: "Malad West",
    city: "Mumbai",
    status: "operational",
    opdCapacityPercent: 55,
    bedsAvailable: { general: 6, icu: 1, observation: 3, total: 15, occupied: 5, reserved: 0, maintenance: 0 },
    doctorsAvailable: 7,
    doctorsTotal: 9,
    appointmentsToday: 98,
    walkIns: 14,
    cancelledSlots: 6,
    availableSlots: 7,
    avgWaitMinutes: 11,
    departments: ["General Medicine", "Diabetology", "Primary Care"],
  },
  {
    id: "h5",
    name: "Sunrise Hospital",
    area: "Thane West",
    city: "Mumbai",
    status: "operational",
    opdCapacityPercent: 71,
    bedsAvailable: { general: 9, icu: 3, observation: 2, total: 30, occupied: 16, reserved: 0, maintenance: 0 },
    doctorsAvailable: 8,
    doctorsTotal: 11,
    appointmentsToday: 127,
    walkIns: 22,
    cancelledSlots: 5,
    availableSlots: 5,
    avgWaitMinutes: 16,
    departments: ["Endocrinology", "Diabetology", "Vascular Surgery"],
  },
];

// ─── DOCTORS ─────────────────────────────────────────────────────────────────
export const defaultDoctors: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    opdRoom: "OPD 02",
    available: true,
    availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    availableHours: "09:00 AM - 02:00 PM",
    experienceYears: 14,
    patientsToday: 42,
    waitingPatients: 6,
    inConsultation: 1,
    completed: 27,
    cancelled: 2,
    avgWaitMinutes: 18,
    qualifications: "MD, DM (Endocrinology), PGIMER",
  },
  {
    id: "d2",
    name: "Dr. Rajesh Sharma",
    specialty: "Diabetology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    opdRoom: "OPD 03",
    available: true,
    availableDays: ["Monday", "Wednesday", "Friday", "Saturday"],
    availableHours: "10:00 AM - 04:00 PM",
    experienceYears: 11,
    patientsToday: 38,
    waitingPatients: 8,
    inConsultation: 1,
    completed: 29,
    cancelled: 0,
    avgWaitMinutes: 12,
    qualifications: "MBBS, MD (Medicine), Dip. Diabetology",
  },
  {
    id: "d3",
    name: "Dr. Priya Mehta",
    specialty: "Internal Medicine",
    hospitalId: "h2",
    hospitalName: "Metro Hospital",
    opdRoom: "OPD 01",
    available: true,
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    availableHours: "09:30 AM - 01:30 PM",
    experienceYears: 9,
    patientsToday: 35,
    waitingPatients: 6,
    inConsultation: 1,
    completed: 28,
    cancelled: 0,
    avgWaitMinutes: 14,
    qualifications: "MBBS, MD (Internal Medicine)",
  },
  {
    id: "d4",
    name: "Dr. Sunil Patil",
    specialty: "Endocrinology",
    hospitalId: "h3",
    hospitalName: "Central Hospital",
    opdRoom: "OPD 01",
    available: true,
    availableDays: ["Monday", "Tuesday", "Thursday", "Friday"],
    availableHours: "08:30 AM - 01:00 PM",
    experienceYears: 16,
    patientsToday: 48,
    waitingPatients: 16,
    inConsultation: 2,
    completed: 28,
    cancelled: 2,
    avgWaitMinutes: 41,
    qualifications: "MD, DM (Endocrinology)",
  },
];

// ─── INITIAL APPOINTMENTS ─────────────────────────────────────────────────────
export const defaultAppointments: Appointment[] = [
  {
    id: "apt-001",
    patientId: "DIA-204829",
    patientName: "Rahul Sharma",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    department: "Endocrinology",
    date: "2026-10-03",
    time: "10:30 AM",
    token: 18,
    status: "waiting",
    type: "follow-up",
    createdAt: "2026-10-01T09:00:00Z",
  },
  {
    id: "apt-002",
    patientId: "DIA-204829",
    patientName: "Rahul Sharma",
    doctorId: "d3",
    doctorName: "Dr. Priya Mehta",
    specialty: "Internal Medicine",
    hospitalId: "h2",
    hospitalName: "Metro Hospital",
    department: "Internal Medicine",
    date: "2026-09-10",
    time: "11:00 AM",
    token: 8,
    status: "completed",
    type: "regular",
    createdAt: "2026-09-05T10:00:00Z",
  },
  {
    id: "apt-003",
    patientId: "DIA-204829",
    patientName: "Rahul Sharma",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    department: "Endocrinology",
    date: "2026-08-20",
    time: "09:30 AM",
    token: 5,
    status: "completed",
    type: "regular",
    createdAt: "2026-08-15T11:30:00Z",
  },
  {
    id: "apt-004",
    patientId: "DIA-205134",
    patientName: "Fatima Shaikh",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    department: "Endocrinology",
    date: "2026-10-03",
    time: "10:45 AM",
    token: 19,
    status: "waiting",
    type: "regular",
    createdAt: "2026-10-02T08:00:00Z",
  },
  {
    id: "apt-005",
    patientId: "DIA-205890",
    patientName: "Amit Patil",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    department: "Endocrinology",
    date: "2026-10-03",
    time: "11:00 AM",
    token: 20,
    status: "upcoming",
    type: "regular",
    createdAt: "2026-10-02T09:30:00Z",
  },
];

// ─── INITIAL LIVE QUEUE ───────────────────────────────────────────────────────
export const defaultLiveQueue: QueueEntry[] = [
  { token: 12, patientId: "DIA-203001", patientName: "Kavya Nair", appointmentTime: "10:00 AM", doctorId: "d1", status: "in-consultation", waitMinutes: 0, appointmentId: "apt-100" },
  { token: 13, patientId: "DIA-203211", patientName: "Suresh Iyer", appointmentTime: "10:15 AM", doctorId: "d1", status: "called", waitMinutes: 4, appointmentId: "apt-101" },
  { token: 14, patientId: "DIA-203522", patientName: "Geeta Bhatt", appointmentTime: "10:15 AM", doctorId: "d1", status: "waiting", waitMinutes: 8, appointmentId: "apt-102" },
  { token: 15, patientId: "DIA-203740", patientName: "Ramesh Gupta", appointmentTime: "10:15 AM", doctorId: "d1", status: "waiting", waitMinutes: 12, appointmentId: "apt-103" },
  { token: 16, patientId: "DIA-203912", patientName: "Anita Joshi", appointmentTime: "10:30 AM", doctorId: "d1", status: "waiting", waitMinutes: 16, appointmentId: "apt-104" },
  { token: 17, patientId: "DIA-204102", patientName: "Deepak Malhotra", appointmentTime: "10:30 AM", doctorId: "d1", status: "waiting", waitMinutes: 20, appointmentId: "apt-105" },
  { token: 18, patientId: "DIA-204829", patientName: "Rahul Sharma", appointmentTime: "10:30 AM", doctorId: "d1", status: "waiting", waitMinutes: 24, appointmentId: "apt-001" },
  { token: 19, patientId: "DIA-205134", patientName: "Fatima Shaikh", appointmentTime: "10:45 AM", doctorId: "d1", status: "waiting", waitMinutes: 28, appointmentId: "apt-004" },
  { token: 20, patientId: "DIA-205890", patientName: "Amit Patil", appointmentTime: "11:00 AM", doctorId: "d1", status: "confirmed", waitMinutes: 32, appointmentId: "apt-005" },
];

// ─── INITIAL CONSULTATION RECORDS ───────────────────────────────────────────
export const defaultConsultations: ConsultationRecord[] = [
  {
    id: "c-001",
    appointmentId: "apt-002",
    patientId: "DIA-204829",
    patientName: "Rahul Sharma",
    doctorId: "d3",
    doctorName: "Dr. Priya Mehta",
    hospitalId: "h2",
    hospitalName: "Metro Hospital",
    date: "2026-09-10",
    time: "11:00 AM",
    notes: "Patient reports stable morning readings around 120-130 mg/dL. Encouraged dietary control and 30 min daily walking.",
    observations: "BP 124/82. HbA1c 7.2%. No signs of peripheral neuropathy. Fundus examination clear.",
    followUpDate: "2026-10-15",
    createdAt: "2026-09-10T11:30:00Z",
  },
  {
    id: "c-002",
    appointmentId: "apt-003",
    patientId: "DIA-204829",
    patientName: "Rahul Sharma",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    date: "2026-08-20",
    time: "09:30 AM",
    notes: "Routine quarterly endocrinology review. Adjusted Glimepiride to 1mg OD.",
    observations: "Weight 76kg. Post-meal glucose 154 mg/dL. Patient compliant with medication.",
    followUpDate: "2026-09-24",
    createdAt: "2026-08-20T10:00:00Z",
  },
];

// ─── INITIAL BEDS ─────────────────────────────────────────────────────────────
export const defaultBeds: HospitalBed[] = [
  { id: "BED-101", hospitalId: "h1", hospitalName: "City Diabetes Centre", ward: "Diabetes Care Ward A", floor: "2nd Floor", bedType: "General", status: "occupied", patientName: "Sanjay Verma", patientId: "DIA-901", updatedAt: "2026-10-03T07:00:00Z" },
  { id: "BED-102", hospitalId: "h1", hospitalName: "City Diabetes Centre", ward: "Diabetes Care Ward A", floor: "2nd Floor", bedType: "General", status: "available", updatedAt: "2026-10-03T08:00:00Z" },
  { id: "BED-103", hospitalId: "h1", hospitalName: "City Diabetes Centre", ward: "Diabetes Care Ward A", floor: "2nd Floor", bedType: "General", status: "occupied", patientName: "Nisha Patel", patientId: "DIA-902", updatedAt: "2026-10-03T06:30:00Z" },
  { id: "BED-104", hospitalId: "h1", hospitalName: "City Diabetes Centre", ward: "Diabetes Care Ward B", floor: "2nd Floor", bedType: "General", status: "available", updatedAt: "2026-10-03T08:00:00Z" },
  { id: "BED-105", hospitalId: "h1", hospitalName: "City Diabetes Centre", ward: "ICU Unit 1", floor: "3rd Floor", bedType: "ICU", status: "occupied", patientName: "Harish Rao", patientId: "DIA-903", updatedAt: "2026-10-02T22:00:00Z" },
  { id: "BED-106", hospitalId: "h1", hospitalName: "City Diabetes Centre", ward: "ICU Unit 1", floor: "3rd Floor", bedType: "ICU", status: "available", updatedAt: "2026-10-03T08:00:00Z" },
  { id: "BED-107", hospitalId: "h1", hospitalName: "City Diabetes Centre", ward: "Observation Ward", floor: "1st Floor", bedType: "Observation", status: "reserved", patientName: "Meenakshi K", patientId: "DIA-904", updatedAt: "2026-10-03T07:45:00Z" },
  { id: "BED-108", hospitalId: "h1", hospitalName: "City Diabetes Centre", ward: "Observation Ward", floor: "1st Floor", bedType: "Observation", status: "available", updatedAt: "2026-10-03T08:00:00Z" },
  { id: "BED-201", hospitalId: "h2", hospitalName: "Metro Hospital", ward: "Medical Ward 1", floor: "1st Floor", bedType: "General", status: "occupied", patientName: "Tarun Bajaj", patientId: "DIA-905", updatedAt: "2026-10-03T05:00:00Z" },
  { id: "BED-202", hospitalId: "h2", hospitalName: "Metro Hospital", ward: "Medical Ward 1", floor: "1st Floor", bedType: "General", status: "available", updatedAt: "2026-10-03T08:00:00Z" },
  { id: "BED-203", hospitalId: "h2", hospitalName: "Metro Hospital", ward: "ICU Ward", floor: "2nd Floor", bedType: "ICU", status: "maintenance", updatedAt: "2026-10-03T04:00:00Z" },
  { id: "BED-301", hospitalId: "h3", hospitalName: "Central Hospital", ward: "General Ward A", floor: "1st Floor", bedType: "General", status: "occupied", patientName: "Kamlesh Shah", patientId: "DIA-906", updatedAt: "2026-10-03T06:00:00Z" },
];

// ─── INITIAL STAFF MEMBERS (HRM) ─────────────────────────────────────────────
export const defaultStaffMembers: StaffMember[] = [
  { id: "STF-101", name: "Dr. Ayesha Khan", role: "Doctor", department: "Endocrinology", contact: "+91 98200 11223", email: "ayesha.k@citydiabetes.org", shift: "Morning", availability: "On Duty", status: "Active", hospitalId: "h1", hospitalName: "City Diabetes Centre" },
  { id: "STF-102", name: "Dr. Rajesh Sharma", role: "Doctor", department: "Diabetology", contact: "+91 98200 33445", email: "rajesh.s@citydiabetes.org", shift: "Morning", availability: "On Duty", status: "Active", hospitalId: "h1", hospitalName: "City Diabetes Centre" },
  { id: "STF-103", name: "Nurse Sunita Rane", role: "Nurse", department: "OPD Nursing", contact: "+91 98200 55667", email: "sunita.r@citydiabetes.org", shift: "Morning", availability: "On Duty", status: "Active", hospitalId: "h1", hospitalName: "City Diabetes Centre" },
  { id: "STF-104", name: "Nurse Priya Nair", role: "Nurse", department: "Diabetes Educator", contact: "+91 98200 77889", email: "priya.n@citydiabetes.org", shift: "Evening", availability: "Available", status: "Active", hospitalId: "h1", hospitalName: "City Diabetes Centre" },
  { id: "STF-105", name: "Amit Kumar", role: "Receptionist", department: "OPD Registration", contact: "+91 98200 99001", email: "amit.k@citydiabetes.org", shift: "Morning", availability: "On Duty", status: "Active", hospitalId: "h1", hospitalName: "City Diabetes Centre" },
  { id: "STF-106", name: "Rohan Kulkarni", role: "Technician", department: "Diabetes Lab & CGM", contact: "+91 98200 12345", email: "rohan.k@citydiabetes.org", shift: "Morning", availability: "On Duty", status: "Active", hospitalId: "h1", hospitalName: "City Diabetes Centre" },
  { id: "STF-107", name: "Anjali Gupta", role: "Administrator", department: "Hospital Operations", contact: "+91 98200 23456", email: "anjali.g@citydiabetes.org", shift: "Morning", availability: "On Duty", status: "Active", hospitalId: "h1", hospitalName: "City Diabetes Centre" },
  { id: "STF-108", name: "Dr. Priya Mehta", role: "Doctor", department: "Internal Medicine", contact: "+91 98200 34567", email: "priya.m@metrohospital.org", shift: "Morning", availability: "On Duty", status: "Active", hospitalId: "h2", hospitalName: "Metro Hospital" },
];

// ─── INITIAL OPD DEPARTMENTS ─────────────────────────────────────────────────
export const defaultOpdDepartments: OpdDepartment[] = [
  {
    id: "opd-dep-1",
    hospitalId: "h1",
    name: "Endocrinology",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    workingHours: "09:00 AM - 02:00 PM",
    slotDurationMinutes: 15,
    maxPatientsPerSlot: 1,
    isOpen: true,
    slots: ["09:00 AM", "09:15 AM", "09:30 AM", "09:45 AM", "10:00 AM", "10:15 AM", "10:30 AM", "10:45 AM", "11:00 AM", "11:15 AM", "11:30 AM", "11:45 AM", "12:00 PM", "12:15 PM"],
  },
  {
    id: "opd-dep-2",
    hospitalId: "h1",
    name: "Diabetology",
    doctorId: "d2",
    doctorName: "Dr. Rajesh Sharma",
    workingHours: "10:00 AM - 04:00 PM",
    slotDurationMinutes: 20,
    maxPatientsPerSlot: 1,
    isOpen: true,
    slots: ["10:00 AM", "10:20 AM", "10:40 AM", "11:00 AM", "11:20 AM", "11:40 AM", "12:00 PM", "12:20 PM", "02:00 PM", "02:20 PM", "02:40 PM"],
  },
  {
    id: "opd-dep-3",
    hospitalId: "h2",
    name: "Internal Medicine",
    doctorId: "d3",
    doctorName: "Dr. Priya Mehta",
    workingHours: "09:30 AM - 01:30 PM",
    slotDurationMinutes: 15,
    maxPatientsPerSlot: 1,
    isOpen: true,
    slots: ["09:30 AM", "09:45 AM", "10:00 AM", "10:15 AM", "10:30 AM", "11:00 AM", "11:15 AM", "11:30 AM"],
  },
];

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
export const defaultNotifications: Notification[] = [
  {
    id: "n1",
    type: "info",
    title: "Appointment Confirmed",
    message: "Your appointment with Dr. Ayesha Khan at City Diabetes Centre on 03 Oct is confirmed. Token #18.",
    timestamp: "Today, 8:30 AM",
    read: false,
  },
  {
    id: "n2",
    type: "warning",
    title: "OPD Queue Status Update",
    message: "Dr. Khan's OPD is currently serving Token #12. Estimated wait for Token #18 is 24 min.",
    timestamp: "Today, 10:05 AM",
    read: false,
  },
  {
    id: "n3",
    type: "success",
    title: "Glucose Reading Recorded",
    message: "Fasting reading of 118 mg/dL added successfully to your Diabetes Care Timeline.",
    timestamp: "Today, 08:15 AM",
    read: true,
  },
];

// ─── AUDIT TRAIL ──────────────────────────────────────────────────────────────
export const defaultAuditEvents: AuditEvent[] = [
  {
    id: "au1",
    timestamp: "08:15 AM",
    user: "Rahul Sharma",
    userRole: "patient",
    action: "Recorded Fasting Glucose — 118 mg/dL",
    facility: "Patient Portal",
    patientId: "DIA-204829",
    status: "completed",
  },
  {
    id: "au2",
    timestamp: "10:21 AM",
    user: "Dr. Ayesha Khan",
    userRole: "doctor",
    action: "Accessed patient record — Rahul Sharma (DIA-204829)",
    facility: "City Diabetes Centre",
    patientId: "DIA-204829",
    status: "completed",
  },
  {
    id: "au3",
    timestamp: "10:30 AM",
    user: "Dr. Ayesha Khan",
    userRole: "doctor",
    action: "Started consultation — Kavya Nair (Token #12)",
    facility: "City Diabetes Centre",
    status: "completed",
  },
];

// ─── AI RECOMMENDATIONS ───────────────────────────────────────────────────────
export const defaultAiRecommendations: AIRecommendation[] = [
  {
    id: "ai1",
    type: "slot-fill",
    title: "Cancellation Slot Re-allocation",
    description: "Slot opened at 11:30 AM. Waiting patient DIA-205134 can be moved forward.",
    reason: [
      "Patient waiting for 28 minutes",
      "Matches Dr. Khan's OPD availability",
      "Optimal OPD throughput recovery",
    ],
    status: "pending",
    timestamp: "10:45 AM",
  },
  {
    id: "ai2",
    type: "bottleneck",
    title: "OPD Load Warning — Central Hospital",
    description: "Central Hospital OPD operating at 94% capacity.",
    reason: [
      "Average wait reached 41 minutes",
      "Suggest rerouting non-critical follow-ups to Metro Hospital (14 min wait)",
      "Requires human coordinator approval",
    ],
    status: "pending",
    timestamp: "10:50 AM",
  },
];

// ─── NETWORK STATS ────────────────────────────────────────────────────────────
export const defaultNetworkStats: NetworkStats = {
  connectedHospitals: 5,
  activeDoctors: 47,
  totalPatients: 84291,
  appointmentsToday: 2481,
  avgWaitMinutes: 18,
  availableBeds: 45,
  utilizationPercent: 78,
};

// ─── CAPACITY TREND ────────────────────────────────────────────────────────────
export const capacityTrend = [
  { time: "8:00 AM", capacity: 45, wait: 8 },
  { time: "9:00 AM", capacity: 62, wait: 12 },
  { time: "10:00 AM", capacity: 78, wait: 18 },
  { time: "11:00 AM", capacity: 82, wait: 22 },
  { time: "12:00 PM", capacity: 88, wait: 28 },
  { time: "01:00 PM", capacity: 75, wait: 20 },
  { time: "02:00 PM", capacity: 65, wait: 15 },
  { time: "03:00 PM", capacity: 50, wait: 10 },
];

// ─── RECORD ACCESS ─────────────────────────────────────────────────────────────
export const recordAccess: RecordAccess[] = [
  {
    by: "Dr. Ayesha Khan",
    role: "Endocrinologist",
    facility: "City Diabetes Centre",
    timestamp: "Today, 10:21 AM",
    authorized: true,
  },
  {
    by: "Dr. Priya Mehta",
    role: "Internal Medicine",
    facility: "Metro Hospital",
    timestamp: "10 Sep 2026, 11:05 AM",
    authorized: true,
  },
];

export const networkHospitalTable = [
  { name: "City Diabetes Centre", opdLoad: 82, slots: 4, beds: 18, doctors: 12, wait: 18, status: "operational" },
  { name: "Metro Hospital", opdLoad: 67, slots: 8, beds: 11, doctors: 9, wait: 14, status: "operational" },
  { name: "Central Hospital", opdLoad: 94, slots: 0, beds: 3, doctors: 6, wait: 41, status: "high-load" },
  { name: "Community Health Centre", opdLoad: 55, slots: 7, beds: 10, doctors: 7, wait: 11, status: "operational" },
  { name: "Sunrise Hospital", opdLoad: 71, slots: 5, beds: 14, doctors: 8, wait: 16, status: "operational" },
];
