import {
  Patient,
  Doctor,
  Hospital,
  Appointment,
  QueueEntry,
  Notification,
  AuditEvent,
  AIRecommendation,
  NetworkStats,
  VisitRecord,
  RecordAccess,
} from "./types";

// ─── HOSPITALS ────────────────────────────────────────────────────────────────
export const hospitals: Hospital[] = [
  {
    id: "h1",
    name: "City Diabetes Centre",
    area: "Bandra West",
    city: "Mumbai",
    status: "operational",
    opdCapacityPercent: 82,
    bedsAvailable: { general: 12, icu: 2, observation: 4 },
    doctorsAvailable: 12,
    doctorsTotal: 15,
    appointmentsToday: 184,
    walkIns: 27,
    cancelledSlots: 9,
    availableSlots: 4,
    avgWaitMinutes: 18,
  },
  {
    id: "h2",
    name: "Metro Hospital",
    area: "Andheri East",
    city: "Mumbai",
    status: "operational",
    opdCapacityPercent: 67,
    bedsAvailable: { general: 8, icu: 1, observation: 2 },
    doctorsAvailable: 9,
    doctorsTotal: 12,
    appointmentsToday: 152,
    walkIns: 19,
    cancelledSlots: 4,
    availableSlots: 8,
    avgWaitMinutes: 14,
  },
  {
    id: "h3",
    name: "Central Hospital",
    area: "Dadar",
    city: "Mumbai",
    status: "high-load",
    opdCapacityPercent: 94,
    bedsAvailable: { general: 2, icu: 0, observation: 1 },
    doctorsAvailable: 6,
    doctorsTotal: 10,
    appointmentsToday: 201,
    walkIns: 38,
    cancelledSlots: 2,
    availableSlots: 0,
    avgWaitMinutes: 41,
  },
  {
    id: "h4",
    name: "Community Health Centre",
    area: "Malad West",
    city: "Mumbai",
    status: "operational",
    opdCapacityPercent: 55,
    bedsAvailable: { general: 6, icu: 1, observation: 3 },
    doctorsAvailable: 7,
    doctorsTotal: 9,
    appointmentsToday: 98,
    walkIns: 14,
    cancelledSlots: 6,
    availableSlots: 7,
    avgWaitMinutes: 11,
  },
  {
    id: "h5",
    name: "Sunrise Hospital",
    area: "Thane West",
    city: "Mumbai",
    status: "operational",
    opdCapacityPercent: 71,
    bedsAvailable: { general: 9, icu: 3, observation: 2 },
    doctorsAvailable: 8,
    doctorsTotal: 11,
    appointmentsToday: 127,
    walkIns: 22,
    cancelledSlots: 5,
    availableSlots: 5,
    avgWaitMinutes: 16,
  },
];

// ─── DOCTORS ─────────────────────────────────────────────────────────────────
export const doctors: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    opdRoom: "OPD 02",
    available: true,
    patientsToday: 42,
    waitingPatients: 11,
    inConsultation: 2,
    completed: 27,
    cancelled: 2,
    avgWaitMinutes: 18,
    qualifications: "MD, DM (Endocrinology), PGIMER",
  },
  {
    id: "d2",
    name: "Dr. Rajesh Sharma",
    specialty: "Diabetology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    opdRoom: "OPD 03",
    available: true,
    patientsToday: 38,
    waitingPatients: 8,
    inConsultation: 1,
    completed: 29,
    cancelled: 0,
    avgWaitMinutes: 12,
    qualifications: "MBBS, MD (Medicine), Dip. Diabetology",
  },
  {
    id: "d3",
    name: "Dr. Priya Mehta",
    specialty: "Internal Medicine",
    hospitalId: "h2",
    hospitalName: "Metro Hospital",
    opdRoom: "OPD 01",
    available: true,
    patientsToday: 35,
    waitingPatients: 6,
    inConsultation: 1,
    completed: 28,
    cancelled: 0,
    avgWaitMinutes: 14,
    qualifications: "MBBS, MD (Internal Medicine)",
  },
  {
    id: "d4",
    name: "Dr. Sunil Patil",
    specialty: "Endocrinology",
    hospitalId: "h3",
    hospitalName: "Central Hospital",
    opdRoom: "OPD 01",
    available: true,
    patientsToday: 48,
    waitingPatients: 16,
    inConsultation: 2,
    completed: 28,
    cancelled: 2,
    avgWaitMinutes: 41,
    qualifications: "MD, DM (Endocrinology)",
  },
];

// ─── PATIENTS ─────────────────────────────────────────────────────────────────
export const patients: Patient[] = [
  {
    id: "DIA-204829",
    name: "Rahul Sharma",
    age: 47,
    gender: "Male",
    phone: "+91 98765 43210",
    email: "rahul.s@email.com",
    diabetesType: "Type 2",
    connectedHospitals: ["h1", "h2", "h4"],
    assignedDoctors: ["d1", "d3"],
    totalVisits: 7,
    documents: 12,
    language: "Hindi",
  },
  {
    id: "DIA-205134",
    name: "Fatima Shaikh",
    age: 38,
    gender: "Female",
    phone: "+91 91234 56789",
    diabetesType: "Type 2",
    connectedHospitals: ["h1", "h3"],
    assignedDoctors: ["d1"],
    totalVisits: 4,
    documents: 7,
    language: "Urdu",
  },
  {
    id: "DIA-205890",
    name: "Amit Patil",
    age: 54,
    gender: "Male",
    phone: "+91 99887 76655",
    diabetesType: "Type 1",
    connectedHospitals: ["h1", "h2"],
    assignedDoctors: ["d2", "d3"],
    totalVisits: 12,
    documents: 18,
    language: "Marathi",
  },
  {
    id: "DIA-206271",
    name: "Sunita Desai",
    age: 62,
    gender: "Female",
    phone: "+91 87654 32109",
    diabetesType: "Type 2",
    connectedHospitals: ["h2", "h4"],
    assignedDoctors: ["d3"],
    totalVisits: 9,
    documents: 15,
    language: "English",
    caregiverAccess: {
      name: "Vikram Desai",
      relationship: "Son",
      permissions: ["appointments", "queue", "notifications"],
      authorized: true,
    },
  },
  {
    id: "DIA-207443",
    name: "Mohammad Ansari",
    age: 51,
    gender: "Male",
    phone: "+91 77654 32198",
    diabetesType: "Pre-diabetes",
    connectedHospitals: ["h1"],
    assignedDoctors: ["d1"],
    totalVisits: 3,
    documents: 5,
    language: "Urdu",
  },
];

// ─── QUEUE ────────────────────────────────────────────────────────────────────
export const liveQueue: QueueEntry[] = [
  { token: 12, patientId: "DIA-203001", patientName: "Kavya Nair", appointmentTime: "10:00", status: "in-consultation", waitMinutes: 0 },
  { token: 13, patientId: "DIA-203211", patientName: "Suresh Iyer", appointmentTime: "10:15", status: "called", waitMinutes: 5 },
  { token: 14, patientId: "DIA-203522", patientName: "Geeta Bhatt", appointmentTime: "10:15", status: "waiting", waitMinutes: 10 },
  { token: 15, patientId: "DIA-203740", patientName: "Ramesh Gupta", appointmentTime: "10:15", status: "waiting", waitMinutes: 15 },
  { token: 16, patientId: "DIA-203912", patientName: "Anita Joshi", appointmentTime: "10:30", status: "waiting", waitMinutes: 18 },
  { token: 17, patientId: "DIA-204102", patientName: "Deepak Malhotra", appointmentTime: "10:30", status: "waiting", waitMinutes: 22 },
  { token: 18, patientId: "DIA-204829", patientName: "Rahul Sharma", appointmentTime: "10:30", status: "waiting", waitMinutes: 24 },
  { token: 19, patientId: "DIA-205134", patientName: "Fatima Shaikh", appointmentTime: "10:45", status: "waiting", waitMinutes: 31 },
  { token: 20, patientId: "DIA-205890", patientName: "Amit Patil", appointmentTime: "11:00", status: "confirmed", waitMinutes: 0 },
  { token: 21, patientId: "DIA-206271", patientName: "Sunita Desai", appointmentTime: "11:15", status: "confirmed", waitMinutes: 0 },
  { token: 22, patientId: "DIA-207443", patientName: "Mohammad Ansari", appointmentTime: "11:30", status: "confirmed", waitMinutes: 0 },
];

// ─── APPOINTMENTS ─────────────────────────────────────────────────────────────
export const appointments: Appointment[] = [
  {
    id: "apt-001",
    patientId: "DIA-204829",
    patientName: "Rahul Sharma",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    date: "2026-09-24",
    time: "10:30 AM",
    token: 18,
    status: "waiting",
    type: "follow-up",
  },
  {
    id: "apt-002",
    patientId: "DIA-204829",
    patientName: "Rahul Sharma",
    doctorId: "d3",
    doctorName: "Dr. Priya Mehta",
    specialty: "Internal Medicine",
    hospitalId: "h2",
    hospitalName: "Metro Hospital",
    date: "2026-09-10",
    time: "11:00 AM",
    token: 8,
    status: "completed",
    type: "regular",
  },
  {
    id: "apt-003",
    patientId: "DIA-204829",
    patientName: "Rahul Sharma",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    date: "2026-08-20",
    time: "09:30 AM",
    token: 5,
    status: "completed",
    type: "regular",
  },
  {
    id: "apt-004",
    patientId: "DIA-204829",
    patientName: "Rahul Sharma",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    date: "2026-07-15",
    time: "10:00 AM",
    token: 12,
    status: "cancelled",
    type: "regular",
  },
  {
    id: "apt-005",
    patientId: "DIA-205134",
    patientName: "Fatima Shaikh",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    date: "2026-09-24",
    time: "10:45 AM",
    token: 19,
    status: "waiting",
    type: "regular",
  },
  {
    id: "apt-006",
    patientId: "DIA-205890",
    patientName: "Amit Patil",
    doctorId: "d1",
    doctorName: "Dr. Ayesha Khan",
    specialty: "Endocrinology",
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    date: "2026-09-24",
    time: "11:00 AM",
    token: 20,
    status: "upcoming",
    type: "regular",
  },
];

// ─── VISIT HISTORY ────────────────────────────────────────────────────────────
export const visitHistory: VisitRecord[] = [
  {
    date: "Sept 2026",
    year: 2026,
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    type: "OPD Visit",
    doctorName: "Dr. Ayesha Khan",
  },
  {
    date: "Sept 2026",
    year: 2026,
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    type: "Uploaded document",
  },
  {
    date: "Aug 2026",
    year: 2026,
    hospitalId: "h1",
    hospitalName: "City Diabetes Centre",
    type: "Follow-up scheduled",
    doctorName: "Dr. Ayesha Khan",
  },
  {
    date: "June 2026",
    year: 2026,
    hospitalId: "h2",
    hospitalName: "Metro Hospital",
    type: "OPD Visit",
    doctorName: "Dr. Priya Mehta",
  },
  {
    date: "Jan 2026",
    year: 2026,
    hospitalId: "h4",
    hospitalName: "Community Health Centre",
    type: "Consultation record",
  },
  {
    date: "Nov 2025",
    year: 2025,
    hospitalId: "h2",
    hospitalName: "Metro Hospital",
    type: "OPD Visit",
    doctorName: "Dr. Priya Mehta",
  },
  {
    date: "Aug 2025",
    year: 2025,
    hospitalId: "h2",
    hospitalName: "Metro Hospital",
    type: "Discharge document",
  },
];

// ─── RECORD ACCESS ─────────────────────────────────────────────────────────────
export const recordAccess: RecordAccess[] = [
  {
    by: "Dr. Ayesha Khan",
    role: "Endocrinologist",
    facility: "City Diabetes Centre",
    timestamp: "Today, 10:21 AM",
    authorized: true,
  },
  {
    by: "Dr. Priya Mehta",
    role: "Internal Medicine",
    facility: "Metro Hospital",
    timestamp: "10 Sep 2026, 11:05 AM",
    authorized: true,
  },
  {
    by: "Hospital Admin",
    role: "Administrative Staff",
    facility: "City Diabetes Centre",
    timestamp: "24 Sep 2026, 9:00 AM",
    authorized: true,
  },
];

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
export const notifications: Notification[] = [
  {
    id: "n1",
    type: "info",
    title: "Appointment Confirmed",
    message: "Your appointment with Dr. Ayesha Khan at City Diabetes Centre on 24 Sep is confirmed. Token #18.",
    timestamp: "Today, 8:30 AM",
    read: false,
  },
  {
    id: "n2",
    type: "warning",
    title: "OPD Running Late",
    message: "Dr. Khan's OPD is running approximately 12 minutes behind schedule. Estimated wait is 24 min.",
    timestamp: "Today, 10:05 AM",
    read: false,
  },
  {
    id: "n3",
    type: "success",
    title: "Record Access Logged",
    message: "Dr. Ayesha Khan accessed your record at City Diabetes Centre — Today, 10:21 AM.",
    timestamp: "Today, 10:21 AM",
    read: false,
  },
  {
    id: "n4",
    type: "info",
    title: "New Appointment Slot Available",
    message: "A slot opened at 11:30 AM today at City Diabetes Centre. Would you like to take it?",
    timestamp: "Today, 10:45 AM",
    read: true,
  },
  {
    id: "n5",
    type: "success",
    title: "Administrative Request Approved",
    message: "Your caregiver access request for Vikram Desai has been approved.",
    timestamp: "Yesterday, 3:12 PM",
    read: true,
  },
  {
    id: "n6",
    type: "info",
    title: "Hospital Capacity Updated",
    message: "Metro Hospital now has 8 available appointment slots for this week.",
    timestamp: "Yesterday, 9:00 AM",
    read: true,
  },
  {
    id: "n7",
    type: "success",
    title: "Patient Accepted Rescheduled Appointment",
    message: "Rahul Sharma accepted the rescheduled slot at 10:30 AM on 24 Sep.",
    timestamp: "22 Sep, 4:15 PM",
    read: true,
  },
];

// ─── AUDIT TRAIL ──────────────────────────────────────────────────────────────
export const auditEvents: AuditEvent[] = [
  {
    id: "au1",
    timestamp: "10:21 AM",
    user: "Dr. Ayesha Khan",
    userRole: "doctor",
    action: "Accessed patient record — Rahul Sharma (DIA-204829)",
    facility: "City Diabetes Centre",
    patientId: "DIA-204829",
    status: "completed",
  },
  {
    id: "au2",
    timestamp: "10:23 AM",
    user: "Dr. Ayesha Khan",
    userRole: "doctor",
    action: "Appointment rescheduled — Token #15 moved to 10:45 AM",
    facility: "City Diabetes Centre",
    status: "completed",
  },
  {
    id: "au3",
    timestamp: "10:24 AM",
    user: "System (AI-assisted)",
    userRole: "network-admin",
    action: "Patient notified of queue update — Token #18 wait updated to 24 min",
    facility: "City Diabetes Centre",
    patientId: "DIA-204829",
    status: "completed",
    details: "AI-assisted — Human approval was granted",
  },
  {
    id: "au4",
    timestamp: "10:25 AM",
    user: "Admin — City Diabetes Centre",
    userRole: "hospital-admin",
    action: "Slot allocation approved — 11:30 AM slot offered to Token #27",
    facility: "City Diabetes Centre",
    status: "approved",
    details: "AI-assisted recommendation approved by hospital admin",
  },
  {
    id: "au5",
    timestamp: "10:30 AM",
    user: "Dr. Ayesha Khan",
    userRole: "doctor",
    action: "Consultation started — Kavya Nair (Token #12)",
    facility: "City Diabetes Centre",
    status: "completed",
  },
  {
    id: "au6",
    timestamp: "10:47 AM",
    user: "Dr. Ayesha Khan",
    userRole: "doctor",
    action: "Referral requested — Amit Patil to Metro Hospital, Dr. Priya Mehta",
    facility: "City Diabetes Centre",
    patientId: "DIA-205890",
    status: "pending",
  },
  {
    id: "au7",
    timestamp: "10:52 AM",
    user: "Admin — Metro Hospital",
    userRole: "hospital-admin",
    action: "Referral accepted — Slot allocated for Amit Patil",
    facility: "Metro Hospital",
    patientId: "DIA-205890",
    status: "approved",
  },
  {
    id: "au8",
    timestamp: "11:00 AM",
    user: "Dr. Sunil Patil",
    userRole: "doctor",
    action: "Administrative note added — Patient document request sent",
    facility: "Central Hospital",
    status: "completed",
  },
];

// ─── AI RECOMMENDATIONS ───────────────────────────────────────────────────────
export const aiRecommendations: AIRecommendation[] = [
  {
    id: "ai1",
    type: "slot-fill",
    title: "Cancellation Detected at 11:30 AM",
    description: "Patient #27 can be offered the vacant slot.",
    reason: [
      "Patient already waiting 32 minutes",
      "Doctor is available at 11:30 AM",
      "Slot matches standard appointment duration",
    ],
    status: "pending",
    timestamp: "10:45 AM",
  },
  {
    id: "ai2",
    type: "bottleneck",
    title: "OPD Congestion Detected — OPD 03",
    description: "OPD 03 is currently operating 21 minutes behind schedule.",
    reason: [
      "Move next appointment to available doctor (OPD 02)",
      "Notify waiting patients of updated wait time",
      "Open vacant slot for walk-in redistribution",
    ],
    status: "pending",
    timestamp: "10:50 AM",
  },
  {
    id: "ai3",
    type: "reroute",
    title: "Cross-Hospital Capacity Available",
    description: "Central Hospital is at 94% capacity. Metro Hospital has 8 available slots.",
    reason: [
      "Non-urgent appointments can be redirected",
      "Metro Hospital has 14-min average wait vs. 41 min at Central",
      "Patient consent required before any rerouting",
    ],
    status: "pending",
    timestamp: "10:55 AM",
  },
];

// ─── NETWORK STATS ────────────────────────────────────────────────────────────
export const networkStats: NetworkStats = {
  connectedHospitals: 27,
  activeDoctors: 186,
  totalPatients: 84291,
  appointmentsToday: 2481,
  avgWaitMinutes: 19,
  availableBeds: 348,
  utilizationPercent: 78,
};

// ─── AVAILABLE SLOTS ──────────────────────────────────────────────────────────
export const availableSlots = [
  { time: "10:30 AM", doctorId: "d1", type: "regular" },
  { time: "11:15 AM", doctorId: "d1", type: "follow-up" },
  { time: "12:00 PM", doctorId: "d2", type: "regular" },
  { time: "12:30 PM", doctorId: "d2", type: "walk-in" },
];

// ─── NETWORK FLOW DATA ────────────────────────────────────────────────────────
export const flowData = [
  { name: "Appointments", value: 184 },
  { name: "Arrived", value: 167 },
  { name: "Waiting", value: 11 },
  { name: "Consultation", value: 4 },
  { name: "Completed", value: 148 },
  { name: "Delayed", value: 4 },
];

// ─── CAPACITY TREND ────────────────────────────────────────────────────────────
export const capacityTrend = [
  { time: "8:00", capacity: 45, wait: 8 },
  { time: "9:00", capacity: 62, wait: 12 },
  { time: "10:00", capacity: 78, wait: 18 },
  { time: "11:00", capacity: 82, wait: 22 },
  { time: "12:00", capacity: 88, wait: 28 },
  { time: "13:00", capacity: 75, wait: 20 },
  { time: "14:00", capacity: 65, wait: 15 },
  { time: "15:00", capacity: 50, wait: 10 },
];

// ─── NETWORK HOSPITAL TABLE ────────────────────────────────────────────────────
export const networkHospitalTable = [
  { name: "City Diabetes Centre", opdLoad: 82, slots: 4, beds: 18, doctors: 12, wait: 18, status: "operational" },
  { name: "Metro Hospital", opdLoad: 67, slots: 8, beds: 11, doctors: 9, wait: 14, status: "operational" },
  { name: "Central Hospital", opdLoad: 94, slots: 0, beds: 3, doctors: 6, wait: 41, status: "high-load" },
  { name: "Community Health Centre", opdLoad: 55, slots: 7, beds: 10, doctors: 7, wait: 11, status: "operational" },
  { name: "Sunrise Hospital", opdLoad: 71, slots: 5, beds: 14, doctors: 8, wait: 16, status: "operational" },
  { name: "Western Diabetes Clinic", opdLoad: 63, slots: 6, beds: 8, doctors: 6, wait: 13, status: "operational" },
  { name: "Navi Mumbai Medical Centre", opdLoad: 89, slots: 1, beds: 5, doctors: 10, wait: 35, status: "high-load" },
];
